server:
  port: 8146

spring:
  config:
    import: optional:configserver:http://localhost:9297
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://localhost:5434/bankingservice_db
    driver-class-name: org.postgresql.Driver
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
grpc:
  port: 6575