server:
  port: 8146

spring:
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:9297}
  application:
    name: banking-service
  cloud:
    config:
      name: banking-service
  jpa:
    hibernate:
      ddl-auto: validate
grpc:
  port: 6575
springdoc:
  swagger-ui:
    path: /banking/swagger-ui.html