server:
  port: 8146

spring:
  config:
    import: optional:configserver:http://config-server:9297
  application:
    name: banking-service
  cloud:
    config:
      name: banking-service

grpc:
  port: 6575
