server:
  port: 8080
spring:
  config:
    import:
    - optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:9297}
    - optional:classpath:routes.yaml
  application:
    name: gateway-service
  cloud:
    config:
      name: gateway-service