server:
  port: 8080
spring:
  config:
    import:
    - optional:configserver:http://localhost:9297
    - optional:classpath:routes.yaml
  application:
    name: gateway-service

BANKING_ROUTE_URI: http://localhost:8146