USERS_ROUTE_URI: http://localhost:8081
BANKING_ROUTE_URI: http://localhost:8146
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - PrefixPath=/api/v1
      routes:
        - id: sign-up
          uri: ${USERS_ROUTE_URI}
          predicates:
            - Method=POST
            - Path=/auth/signup
        - id: sign-in
          uri: ${USERS_ROUTE_URI}
          predicates:
            - Method=POST
            - Path=/auth/signin
        - id: get-user-details
          uri: ${USERS_ROUTE_URI}
          predicates:
            - Method=GET
            - Header=Authorization, Bearer (.*)
            - Path=/users
        - id: update-user-role
          uri: ${USERS_ROUTE_URI}
          predicates:
            - Method=PATCH
            - Header=Authorization, Bearer (.*)
            - Path=/users/admin
        - id: unblock-user
          uri: ${USERS_ROUTE_URI}
          predicates:
            - Method=POST
            - Header=Authorization, Bearer (.*)
            - Path=/users/unblock/**
        - id: get-all-users
          uri: ${USERS_ROUTE_URI}
          predicates:
            - Method=GET
            - Header=Authorization, Bearer (.*)
            - Path=/users/all
        - id: check-health
          uri: ${USERS_ROUTE_URI}
          predicates:
            - Method=GET
            - Path=/actuator/health
#Banking service routes
        - id: create-card
          uri: ${BANKING_ROUTE_URI}
          predicates:
            - Method=POST
            - Header=Authorization, Bearer (.*)
            - Path=/cards/create
        - id: get-card-by-id
          uri: ${BANKING_ROUTE_URI}
          predicates:
            - Method=GET
            - Header=Authorization, Bearer (.*)
            - Path=/cards/**

        - id: get-wallet
          uri: ${BANKING_ROUTE_URI}
          predicates:
            - Method=GET
            - Header=Authorization, Bearer (.*)
            - Path=/wallet
        - id: delete-wallet
          uri: ${BANKING_ROUTE_URI}
          predicates:
            - Method=DELETE
            - Header=Authorization, Bearer (.*)
            - Path=/wallet/delete

        - id: deposit-transaction
          uri: ${BANKING_ROUTE_URI}
          predicates:
            - Method=POST
            - Header=Authorization, Bearer (.*)
            - Path=/transactions/deposit
        - id: withdrawal-transaction
          uri: ${BANKING_ROUTE_URI}
          predicates:
            - Method=POST
            - Header=Authorization, Bearer (.*)
            - Path=/transactions/withdraw
        - id: transfer-transaction
          uri: ${BANKING_ROUTE_URI}
          predicates:
            - Method=POST
            - Header=Authorization, Bearer (.*)
            - Path=/transactions/transfer
        - id: payment-transaction
          uri: ${BANKING_ROUTE_URI}
          predicates:
            - Method=POST
            - Header=Authorization, Bearer (.*)
            - Path=/transactions/payment
        - id: get-all-transactions
          uri: ${BANKING_ROUTE_URI}
          predicates:
            - Method=GET
            - Header=Authorization, Bearer (.*)
            - Path=/transactions/all*
