server:
  servlet:
    context-path: /api/v1
  port: 8200
spring:
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:9297}
  application:
    name: quartz-service
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          scheduler:
            instanceName: QuartzScheduler
            instanceId: AUTO
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            useProperties: false
            dataSource: quartzDataSource
            tablePrefix: QRTZ_
            isClustered: true
          threadPool:
            threadCount: 5
grpc:
  port: 6585
